//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopee.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shopee.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cuplikan_layar_2026_08_11_131628 {
            get {
                object obj = ResourceManager.GetObject("Cuplikan layar 2026-08-11 131628", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cuplikan_layar_2026_08_11_1316281 {
            get {
                object obj = ResourceManager.GetObject("Cuplikan layar 2026-08-11 1316281", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cuplikan_layar_2026_08_11_131642 {
            get {
                object obj = ResourceManager.GetObject("Cuplikan layar 2026-08-11 131642", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cuplikan_layar_2026_08_11_1316421 {
            get {
                object obj = ResourceManager.GetObject("Cuplikan layar 2026-08-11 1316421", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cuplikan_layar_2026_08_11_131704 {
            get {
                object obj = ResourceManager.GetObject("Cuplikan layar 2026-08-11 131704", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cuplikan_layar_2026_08_11_1317041 {
            get {
                object obj = ResourceManager.GetObject("Cuplikan layar 2026-08-11 1317041", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cuplikan_layar_2026_08_11_132933 {
            get {
                object obj = ResourceManager.GetObject("Cuplikan layar 2026-08-11 132933", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cuplikan_layar_2026_08_11_133741 {
            get {
                object obj = ResourceManager.GetObject("Cuplikan layar 2026-08-11 133741", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cuplikan_layar_2026_08_11_133748 {
            get {
                object obj = ResourceManager.GetObject("Cuplikan layar 2026-08-11 133748", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cuplikan_layar_2026_08_11_1337481 {
            get {
                object obj = ResourceManager.GetObject("Cuplikan layar 2026-08-11 1337481", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cuplikan_layar_2026_08_11_133757 {
            get {
                object obj = ResourceManager.GetObject("Cuplikan layar 2026-08-11 133757", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cuplikan_layar_2026_08_11_134211 {
            get {
                object obj = ResourceManager.GetObject("Cuplikan layar 2026-08-11 134211", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cuplikan_layar_2026_08_11_142044 {
            get {
                object obj = ResourceManager.GetObject("Cuplikan layar 2026-08-11 142044", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cuplikan_layar_2026_08_11_1420441 {
            get {
                object obj = ResourceManager.GetObject("Cuplikan layar 2026-08-11 1420441", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cuplikan_layar_2026_08_11_143500 {
            get {
                object obj = ResourceManager.GetObject("Cuplikan layar 2026-08-11 143500", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cuplikan_layar_2026_08_11_151741 {
            get {
                object obj = ResourceManager.GetObject("Cuplikan layar 2026-08-11 151741", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cuplikan_layar_2026_08_11_1517411 {
            get {
                object obj = ResourceManager.GetObject("Cuplikan layar 2026-08-11 1517411", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cuplikan_layar_2026_08_11_151820 {
            get {
                object obj = ResourceManager.GetObject("Cuplikan layar 2026-08-11 151820", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cuplikan_layar_2026_08_11_1518201 {
            get {
                object obj = ResourceManager.GetObject("Cuplikan layar 2026-08-11 1518201", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cuplikan_layar_2026_08_11_151853 {
            get {
                object obj = ResourceManager.GetObject("Cuplikan layar 2026-08-11 151853", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cuplikan_layar_2026_08_11_1518531 {
            get {
                object obj = ResourceManager.GetObject("Cuplikan layar 2026-08-11 1518531", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cuplikan_layar_2026_08_11_152008 {
            get {
                object obj = ResourceManager.GetObject("Cuplikan layar 2026-08-11 152008", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cuplikan_layar_2026_08_11_1520081 {
            get {
                object obj = ResourceManager.GetObject("Cuplikan layar 2026-08-11 1520081", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cuplikan_layar_2026_08_11_152103 {
            get {
                object obj = ResourceManager.GetObject("Cuplikan layar 2026-08-11 152103", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cuplikan_layar_2026_08_11_1521031 {
            get {
                object obj = ResourceManager.GetObject("Cuplikan layar 2026-08-11 1521031", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cuplikan_layar_2026_08_11_152212 {
            get {
                object obj = ResourceManager.GetObject("Cuplikan layar 2026-08-11 152212", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cuplikan_layar_2026_08_11_1522121 {
            get {
                object obj = ResourceManager.GetObject("Cuplikan layar 2026-08-11 1522121", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cuplikan_layar_2026_08_11_152728 {
            get {
                object obj = ResourceManager.GetObject("Cuplikan layar 2026-08-11 152728", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cuplikan_layar_2026_08_11_152738 {
            get {
                object obj = ResourceManager.GetObject("Cuplikan layar 2026-08-11 152738", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cuplikan_layar_2026_08_11_152748 {
            get {
                object obj = ResourceManager.GetObject("Cuplikan layar 2026-08-11 152748", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Gemini_Generated_Image_59jtrg59jtrg59jt {
            get {
                object obj = ResourceManager.GetObject("Gemini_Generated_Image_59jtrg59jtrg59jt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Gemini_Generated_Image_ij3a5aij3a5aij3a {
            get {
                object obj = ResourceManager.GetObject("Gemini_Generated_Image_ij3a5aij3a5aij3a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Gemini_Generated_Image_ij3a5aij3a5aij3a1 {
            get {
                object obj = ResourceManager.GetObject("Gemini_Generated_Image_ij3a5aij3a5aij3a1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Gemini_Generated_Image_ycpr9cycpr9cycpr {
            get {
                object obj = ResourceManager.GetObject("Gemini_Generated_Image_ycpr9cycpr9cycpr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_vector_notification_icon_png_image_927192 {
            get {
                object obj = ResourceManager.GetObject("pngtree-vector-notification-icon-png-image_927192", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
